### ISSUE TITLE
How to use .blcm files with ModMerger?

### ISSUE THREAD

**Issue by Brad-2509** [juso40/bl2sdk_Mods#10]

**Comment by juso40** [comment]
Ideally you use BLCMM to manage and merge your mods. The ModMerger is mainly a modders ressource.
But if you really want to use it:
1. Place all your .blcm files that you want to enable into the Mod Merger directory (Subfolders will work too)
2. Enable the Mod Merger ingame.
3. Enjoy.

But keep in mind that your files will be merged in alphabetical order, that means if file `a.blcm` and `b.blcm` both edit the same object, only `b.blcm`s changes will take affect. This is th same behavior as in BLCMM, only that you dont have a good visual indicator of wich mod overwrites wich.
