### ISSUE TITLE
Pokelands enemies not spawning

### ISSUE THREAD

**Issue by RobertVorback** [juso40/bl2sdk_Mods#11]
Hello, when I use the pokeball grenade to spawn
friendly npc, I find that normal enemies stop spawning
except for some scripted bosses. If I travel to another
map the enemies will spawn as expected

**Comment by juso40** [comment]
That mod was never intended for a full playthrough. It was more of a test to see if its possible to spawn enemies. I won't update the mod, so don't expect a fix for this issue. Sorry.

**Comment by RobertVorback** [comment]
I understand, and thank you
