### ISSUE TITLE
Pokelands npc is counted as enemy

### ISSUE THREAD

**Issue by RobertVorback** [juso40/bl2sdk_Mods#12]
Certain parts of the game require all enemies to be killed
before proceeding, I find that if there are any npc that are still alive that the scripted event will not proceed.
For example escorting Claptrap to his ship you have to
kill all the bandits before Claptrap moves to the stairs
and tells you to find the elevator control.
If you have any active npc here he will not proceed.
It seems as though the game will only recognise the player and co-op players, but counts npc spawned with the pokeball as enemies

Is there any way to remove or kill an npc after spawning it?

**Comment by juso40** [comment]
Answered in #11 
Won't fix.
