### ISSUE TITLE
LootMarker not working

### ISSUE THREAD

**Issue by pofffu** [juso40/bl2sdk_Mods#15]
I installed the LootMarker mod, tried to use it, cant see it in the mods tab in bl2, Its in the right folder and I've tried reinstalling it, I made sure that my pythonSDK was properly installed and installed a few other SDK mods to make sure it was correctly installed, I even reinstalled it to no avail. Any help is appreciated, Thank you.

**Comment by juso40** [comment]
Do you get any errors in the ingame console?

**Comment by pofffu** [comment]
![Capture](https://user-images.githubusercontent.com/107582935/173917871-fecc809e-4917-40be-a597-82e0f5576020.PNG)

Never thought to actually read my console but yes I do get an error.

**Comment by juso40** [comment]
You need to update the SDK

**Comment by pofffu** [comment]
Wow okay, It works, Thank you tons, I figured out where i messed up while updating it.
