### ISSUE TITLE
BL2 Eternal making bosses disappear

### ISSUE THREAD

**Issue by JackDaDripper** [juso40/bl2sdk_Mods#22]
when i was killing Jack and the Warrior, Jack got teleported into the lava just beside the exit to Eridium Blight.

and when the Warrior was at 15% hp, he dove into the lava and never came back up.
![20220816225706_1](https://user-images.githubusercontent.com/111211274/185038122-371c54d6-dda0-4185-99f0-654909e1605b.jpg)

attached image is the current state im stuck in, i've reloaded the game 4 times and the result is the same

**Comment by juso40** [comment]
What version of BL2 Eternal are you using?

**Comment by JackDaDripper** [comment]
Version 1.3

**Comment by JackDaDripper** [comment]
> What version of BL2 Eternal are you using?

1.3
also, i've been having issues with other enemies when they enter the glory kill health range.
The Leviathan disappears after the queen worm section.
Sand worms are being put into unkillable locations, like the ground or far off out of bounds. 

I'll update the list if i find any more

**Comment by juso40** [comment]
I've removed any sort of AI manipulation in the newest update, so this issue should not persist anymore.
