### ISSUE TITLE
BL2 Eternal Varkid Glory Kill Fatal Error

### ISSUE THREAD

**Issue by ruthlessant** [juso40/bl2sdk_Mods#23]
When a Varkid pods and I kill it whilst its podded with BL2 Eternal enabled the game gives me a Fatal Error and closes the game. It works perfectly fine without BL2 Eternal enabled. After some testing this only seems to happen after I shoot the pod with a Double Penetrating Unkempt Harold, any other weapon is fine.
![image](https://user-images.githubusercontent.com/114843429/193436141-f9466409-5dc6-4d54-8ea4-919a98918f46.png)

**Comment by juso40** [comment]
What version are you using? Try updating.

**Comment by ruthlessant** [comment]
I only downloaded Eternal yesterday so I am using the latest version from githib. I just tried redownloading it but I still get the same issue.

**Comment by danylopez123** [comment]
I downloaded the latest version v1.4 and the same crash happens to me.
For now i disabled the Glory Kills and only kept the air dashing.

**Comment by Fumariano** [comment]
I've got this same issue. Whenever varkids are involved, even without pods. Just shorting them while the mod is on triggers CTD. I'm also running bl2.5.

**Comment by juso40** [comment]
Fixed in v1.5.0
