### ISSUE TITLE
FirstPersonDriver not working on TPS

### ISSUE THREAD

**Issue by TheSanguineMan** [juso40/bl2sdk_Mods#29]
I have used this mod on Borderlands 2 without issue and enjoyed it. For some reason, I can't get the mod to work on The Pre-Sequel even though it is listed to work on it. I have disabled, re-enabled, deleted and, fresh installed but nothing worked. Thank you for your time and I hope to be able to use it.

**Comment by juso40** [comment]
Oh my bad, the mod is not actually compatible with TPS. Will remove TPS from the list of its compatible games.
