### ISSUE TITLE
InventoryEditor incompatible with "AsyncUtil"

### ISSUE THREAD

**Issue by nath30** [juso40/bl2sdk_Mods#4]
InventoryEditor will crash borderlands or not work when [AsyncUtil](https://bl-sdk.github.io/mods/AsyncUtil/) is installed

**Comment by juso40** [comment]
yea, its a limitation of my PydImgui library. Or rather a limitation of Pythons GIL. I dont think i can fix it from my code, but Ill send Apple a potentila compatibility fix for his AsyncUtils
