### ISSUE TITLE
Custom map doesn't load after creating a new lvl 30 character.

### ISSUE THREAD

**Issue by rodrigopbrandao** [juso40/bl2sdk_Mods#41]
I have the mod installed and enabled inside the game, but when I start a new level 30 character, it spawns in the fight for sanctury map (Default for Borlderlands 2) , like the mod wasn't installed. Does anybody knows how to fix this? Thanks.

**Comment by juso40** [comment]
What mod are you running and what are you expecting to happen? If you are planning on playing the Roguelands mod from Pyrex/Joltz check out his [Tutorial on YouTube](https://www.youtube.com/watch?v=mOd01whwkiY)

**Comment by rodrigopbrandao** [comment]
Thanks for the answer @juso40 . Yes I am running the Roguelands mod and that was the exactly youtube tutorial I followed, and since it didn't worked for me I opened this thread.

**Comment by juso40** [comment]
The maploader itself does not move you to the custom maps, its part of Roguelands, so if that isn't working maybe your install is faulty. Check joltz discord and ask in the Roguelands channel for help. A screenshot of the ingame console might be helpful as it might show some errors
