### ISSUE TITLE
Nothing shows up?

### ISSUE THREAD

**Issue by Makekel** [juso40/bl2sdk_Mods#5]
Upon hitting the keybind to open the editor, nothing happens aside from the game locking my mouse movement. I can walk around, sprint, jump, melee, shoot, but I can't move my cursor. If I press the bind again it goes back to normal.

**Comment by juso40** [comment]
If you are on AMD try this proposed [workaround](https://www.microsoft.com/de-DE/download/details.aspx?id=30679)

**Comment by Makekel** [comment]
I downloaded and installed that but nothing changed. Am I doing something wrong? What workaround?

**Comment by juso40** [comment]
I accidentally linked to the wrong thing above, oops. I edited the message to link to the right place :)
Some other thing you can try are starting the game in windowed/borderless instead of exclusive fullscreen.

**Comment by Makekel** [comment]
I got it to work briefly... but after a break and coming back I still have the same issue. I always launch the game in fullscreen windowed, so I tried windowed but that didn't seem to do anything.

**Comment by juso40** [comment]
The I'm out of ideas for now... For other people it works flawless, for me it only works in borderless windowed fullscreen.
You probably will have to wait for me (or someone else) to finally fix the issue. But for now I'm really out of ideas as to what could cause the issue.

**Comment by juso40** [comment]
This issue should be fixed in the newest version of PyImgui, (1.2)
