### ISSUE TITLE
CVM: Scopes don't render with CVM enabled 

### ISSUE THREAD

**Issue by depdas2** [juso40/bl2sdk_Mods#7]
Sniper scopes and other scopes that render an overlay on the screen don't render with the CVM mod enabled. 

I believe that CVM is the mod causing this issue here, I had disabled every other mod that I could, disabling CVM does fix the scope issue. I'm running Python SDK Version 0.7.9 and the CVM mod from this repository. 

Edit: I figured out how to use Github again and downloaded the old version of CVM, it looks like the scopes are working fine there.

**Comment by juso40** [comment]
Fixed in [Version 2.1](https://github.com/juso40/bl2sdk_Mods/tree/master/ConfigurableViewmodel).
